//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8745
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="ACSliteNBIBinding", Namespace="urn:www.acslite.com/nbi:1.5")]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(Array))]
public partial class ACSliteNBI : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback RegisterDeviceOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetDeviceFlagsOperationCompleted;
    
    private System.Threading.SendOrPostCallback SetDeviceFlagsOperationCompleted;
    
    private System.Threading.SendOrPostCallback SendConnectionRequestOperationCompleted;
    
    private System.Threading.SendOrPostCallback QueueCPERequestOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetDeviceCachedParamsOperationCompleted;
    
    private System.Threading.SendOrPostCallback SearchDevicesOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetDeviceOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetDeviceHistoryOperationCompleted;
    
    private System.Threading.SendOrPostCallback DeleteDeviceOperationCompleted;
    
    private System.Threading.SendOrPostCallback CustomSearchOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetDeviceTypesOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetDeviceTypeOperationCompleted;
    
    private System.Threading.SendOrPostCallback DeleteDeviceTypeOperationCompleted;
    
    private System.Threading.SendOrPostCallback ImportDeviceTypeOperationCompleted;
    
    /// <remarks/>
    public ACSliteNBI() {
        this.Url = "http://netcommacs.dyndns.org/nbi.php";
    }
    
    /// <remarks/>
    public event RegisterDeviceCompletedEventHandler RegisterDeviceCompleted;
    
    /// <remarks/>
    public event GetDeviceFlagsCompletedEventHandler GetDeviceFlagsCompleted;
    
    /// <remarks/>
    public event SetDeviceFlagsCompletedEventHandler SetDeviceFlagsCompleted;
    
    /// <remarks/>
    public event SendConnectionRequestCompletedEventHandler SendConnectionRequestCompleted;
    
    /// <remarks/>
    public event QueueCPERequestCompletedEventHandler QueueCPERequestCompleted;
    
    /// <remarks/>
    public event GetDeviceCachedParamsCompletedEventHandler GetDeviceCachedParamsCompleted;
    
    /// <remarks/>
    public event SearchDevicesCompletedEventHandler SearchDevicesCompleted;
    
    /// <remarks/>
    public event GetDeviceCompletedEventHandler GetDeviceCompleted;
    
    /// <remarks/>
    public event GetDeviceHistoryCompletedEventHandler GetDeviceHistoryCompleted;
    
    /// <remarks/>
    public event DeleteDeviceCompletedEventHandler DeleteDeviceCompleted;
    
    /// <remarks/>
    public event CustomSearchCompletedEventHandler CustomSearchCompleted;
    
    /// <remarks/>
    public event GetDeviceTypesCompletedEventHandler GetDeviceTypesCompleted;
    
    /// <remarks/>
    public event GetDeviceTypeCompletedEventHandler GetDeviceTypeCompleted;
    
    /// <remarks/>
    public event DeleteDeviceTypeCompletedEventHandler DeleteDeviceTypeCompleted;
    
    /// <remarks/>
    public event ImportDeviceTypeCompletedEventHandler ImportDeviceTypeCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:www.acslite.com/nbi:1.5", ResponseNamespace="urn:www.acslite.com/nbi:1.5", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("Success")]
    public bool RegisterDevice(DeviceIDStruct DeviceID, DevicePropertiesStruct DeviceProperties) {
        object[] results = this.Invoke("RegisterDevice", new object[] {
                    DeviceID,
                    DeviceProperties});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginRegisterDevice(DeviceIDStruct DeviceID, DevicePropertiesStruct DeviceProperties, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("RegisterDevice", new object[] {
                    DeviceID,
                    DeviceProperties}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndRegisterDevice(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void RegisterDeviceAsync(DeviceIDStruct DeviceID, DevicePropertiesStruct DeviceProperties) {
        this.RegisterDeviceAsync(DeviceID, DeviceProperties, null);
    }
    
    /// <remarks/>
    public void RegisterDeviceAsync(DeviceIDStruct DeviceID, DevicePropertiesStruct DeviceProperties, object userState) {
        if ((this.RegisterDeviceOperationCompleted == null)) {
            this.RegisterDeviceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisterDeviceOperationCompleted);
        }
        this.InvokeAsync("RegisterDevice", new object[] {
                    DeviceID,
                    DeviceProperties}, this.RegisterDeviceOperationCompleted, userState);
    }
    
    private void OnRegisterDeviceOperationCompleted(object arg) {
        if ((this.RegisterDeviceCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.RegisterDeviceCompleted(this, new RegisterDeviceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:www.acslite.com/nbi:1.5", ResponseNamespace="urn:www.acslite.com/nbi:1.5", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("FlagDetailsList")]
    public FlagDetailsList GetDeviceFlags(DeviceIDStruct DeviceID, FlagNameList FlagNames) {
        object[] results = this.Invoke("GetDeviceFlags", new object[] {
                    DeviceID,
                    FlagNames});
        return ((FlagDetailsList)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetDeviceFlags(DeviceIDStruct DeviceID, FlagNameList FlagNames, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetDeviceFlags", new object[] {
                    DeviceID,
                    FlagNames}, callback, asyncState);
    }
    
    /// <remarks/>
    public FlagDetailsList EndGetDeviceFlags(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((FlagDetailsList)(results[0]));
    }
    
    /// <remarks/>
    public void GetDeviceFlagsAsync(DeviceIDStruct DeviceID, FlagNameList FlagNames) {
        this.GetDeviceFlagsAsync(DeviceID, FlagNames, null);
    }
    
    /// <remarks/>
    public void GetDeviceFlagsAsync(DeviceIDStruct DeviceID, FlagNameList FlagNames, object userState) {
        if ((this.GetDeviceFlagsOperationCompleted == null)) {
            this.GetDeviceFlagsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDeviceFlagsOperationCompleted);
        }
        this.InvokeAsync("GetDeviceFlags", new object[] {
                    DeviceID,
                    FlagNames}, this.GetDeviceFlagsOperationCompleted, userState);
    }
    
    private void OnGetDeviceFlagsOperationCompleted(object arg) {
        if ((this.GetDeviceFlagsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetDeviceFlagsCompleted(this, new GetDeviceFlagsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:www.acslite.com/nbi:1.5", ResponseNamespace="urn:www.acslite.com/nbi:1.5", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("Success")]
    public bool SetDeviceFlags(DeviceIDStruct DeviceID, FlagValueList FlagValueList) {
        object[] results = this.Invoke("SetDeviceFlags", new object[] {
                    DeviceID,
                    FlagValueList});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSetDeviceFlags(DeviceIDStruct DeviceID, FlagValueList FlagValueList, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SetDeviceFlags", new object[] {
                    DeviceID,
                    FlagValueList}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndSetDeviceFlags(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void SetDeviceFlagsAsync(DeviceIDStruct DeviceID, FlagValueList FlagValueList) {
        this.SetDeviceFlagsAsync(DeviceID, FlagValueList, null);
    }
    
    /// <remarks/>
    public void SetDeviceFlagsAsync(DeviceIDStruct DeviceID, FlagValueList FlagValueList, object userState) {
        if ((this.SetDeviceFlagsOperationCompleted == null)) {
            this.SetDeviceFlagsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetDeviceFlagsOperationCompleted);
        }
        this.InvokeAsync("SetDeviceFlags", new object[] {
                    DeviceID,
                    FlagValueList}, this.SetDeviceFlagsOperationCompleted, userState);
    }
    
    private void OnSetDeviceFlagsOperationCompleted(object arg) {
        if ((this.SetDeviceFlagsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SetDeviceFlagsCompleted(this, new SetDeviceFlagsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:www.acslite.com/nbi:1.5", ResponseNamespace="urn:www.acslite.com/nbi:1.5", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("AcceptedByDevice")]
    public bool SendConnectionRequest(DeviceIDStruct DeviceID, uint TimeoutSeconds) {
        object[] results = this.Invoke("SendConnectionRequest", new object[] {
                    DeviceID,
                    TimeoutSeconds});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSendConnectionRequest(DeviceIDStruct DeviceID, uint TimeoutSeconds, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SendConnectionRequest", new object[] {
                    DeviceID,
                    TimeoutSeconds}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndSendConnectionRequest(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void SendConnectionRequestAsync(DeviceIDStruct DeviceID, uint TimeoutSeconds) {
        this.SendConnectionRequestAsync(DeviceID, TimeoutSeconds, null);
    }
    
    /// <remarks/>
    public void SendConnectionRequestAsync(DeviceIDStruct DeviceID, uint TimeoutSeconds, object userState) {
        if ((this.SendConnectionRequestOperationCompleted == null)) {
            this.SendConnectionRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendConnectionRequestOperationCompleted);
        }
        this.InvokeAsync("SendConnectionRequest", new object[] {
                    DeviceID,
                    TimeoutSeconds}, this.SendConnectionRequestOperationCompleted, userState);
    }
    
    private void OnSendConnectionRequestOperationCompleted(object arg) {
        if ((this.SendConnectionRequestCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SendConnectionRequestCompleted(this, new SendConnectionRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:www.acslite.com/nbi:1.5", ResponseNamespace="urn:www.acslite.com/nbi:1.5", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("RequestID")]
    public string QueueCPERequest(DeviceIDStruct DeviceID, CPERequestMethod Method, CPERequestParameterList Parameters) {
        object[] results = this.Invoke("QueueCPERequest", new object[] {
                    DeviceID,
                    Method,
                    Parameters});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginQueueCPERequest(DeviceIDStruct DeviceID, CPERequestMethod Method, CPERequestParameterList Parameters, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("QueueCPERequest", new object[] {
                    DeviceID,
                    Method,
                    Parameters}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndQueueCPERequest(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void QueueCPERequestAsync(DeviceIDStruct DeviceID, CPERequestMethod Method, CPERequestParameterList Parameters) {
        this.QueueCPERequestAsync(DeviceID, Method, Parameters, null);
    }
    
    /// <remarks/>
    public void QueueCPERequestAsync(DeviceIDStruct DeviceID, CPERequestMethod Method, CPERequestParameterList Parameters, object userState) {
        if ((this.QueueCPERequestOperationCompleted == null)) {
            this.QueueCPERequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueueCPERequestOperationCompleted);
        }
        this.InvokeAsync("QueueCPERequest", new object[] {
                    DeviceID,
                    Method,
                    Parameters}, this.QueueCPERequestOperationCompleted, userState);
    }
    
    private void OnQueueCPERequestOperationCompleted(object arg) {
        if ((this.QueueCPERequestCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.QueueCPERequestCompleted(this, new QueueCPERequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:www.acslite.com/nbi:1.5", ResponseNamespace="urn:www.acslite.com/nbi:1.5", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("ParameterDetailsList")]
    public ParameterDetailsList GetDeviceCachedParams(DeviceIDStruct DeviceID, ParameterNameList ParameterNames) {
        object[] results = this.Invoke("GetDeviceCachedParams", new object[] {
                    DeviceID,
                    ParameterNames});
        return ((ParameterDetailsList)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetDeviceCachedParams(DeviceIDStruct DeviceID, ParameterNameList ParameterNames, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetDeviceCachedParams", new object[] {
                    DeviceID,
                    ParameterNames}, callback, asyncState);
    }
    
    /// <remarks/>
    public ParameterDetailsList EndGetDeviceCachedParams(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ParameterDetailsList)(results[0]));
    }
    
    /// <remarks/>
    public void GetDeviceCachedParamsAsync(DeviceIDStruct DeviceID, ParameterNameList ParameterNames) {
        this.GetDeviceCachedParamsAsync(DeviceID, ParameterNames, null);
    }
    
    /// <remarks/>
    public void GetDeviceCachedParamsAsync(DeviceIDStruct DeviceID, ParameterNameList ParameterNames, object userState) {
        if ((this.GetDeviceCachedParamsOperationCompleted == null)) {
            this.GetDeviceCachedParamsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDeviceCachedParamsOperationCompleted);
        }
        this.InvokeAsync("GetDeviceCachedParams", new object[] {
                    DeviceID,
                    ParameterNames}, this.GetDeviceCachedParamsOperationCompleted, userState);
    }
    
    private void OnGetDeviceCachedParamsOperationCompleted(object arg) {
        if ((this.GetDeviceCachedParamsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetDeviceCachedParamsCompleted(this, new GetDeviceCachedParamsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:www.acslite.com/nbi:1.5", ResponseNamespace="urn:www.acslite.com/nbi:1.5", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("PaginationDetails")]
    public PaginationDetailsStruct SearchDevices(SearchDevicesQueryStruct SearchQuery, OrderByList OrderByList, PaginationStruct Pagination, out DeviceDetailsList DeviceDetailsList) {
        object[] results = this.Invoke("SearchDevices", new object[] {
                    SearchQuery,
                    OrderByList,
                    Pagination});
        DeviceDetailsList = ((DeviceDetailsList)(results[1]));
        return ((PaginationDetailsStruct)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSearchDevices(SearchDevicesQueryStruct SearchQuery, OrderByList OrderByList, PaginationStruct Pagination, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SearchDevices", new object[] {
                    SearchQuery,
                    OrderByList,
                    Pagination}, callback, asyncState);
    }
    
    /// <remarks/>
    public PaginationDetailsStruct EndSearchDevices(System.IAsyncResult asyncResult, out DeviceDetailsList DeviceDetailsList) {
        object[] results = this.EndInvoke(asyncResult);
        DeviceDetailsList = ((DeviceDetailsList)(results[1]));
        return ((PaginationDetailsStruct)(results[0]));
    }
    
    /// <remarks/>
    public void SearchDevicesAsync(SearchDevicesQueryStruct SearchQuery, OrderByList OrderByList, PaginationStruct Pagination) {
        this.SearchDevicesAsync(SearchQuery, OrderByList, Pagination, null);
    }
    
    /// <remarks/>
    public void SearchDevicesAsync(SearchDevicesQueryStruct SearchQuery, OrderByList OrderByList, PaginationStruct Pagination, object userState) {
        if ((this.SearchDevicesOperationCompleted == null)) {
            this.SearchDevicesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchDevicesOperationCompleted);
        }
        this.InvokeAsync("SearchDevices", new object[] {
                    SearchQuery,
                    OrderByList,
                    Pagination}, this.SearchDevicesOperationCompleted, userState);
    }
    
    private void OnSearchDevicesOperationCompleted(object arg) {
        if ((this.SearchDevicesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SearchDevicesCompleted(this, new SearchDevicesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:www.acslite.com/nbi:1.5", ResponseNamespace="urn:www.acslite.com/nbi:1.5", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("DeviceDetails")]
    public DeviceDetailsStruct GetDevice(DeviceIDStruct GetDeviceQuery) {
        object[] results = this.Invoke("GetDevice", new object[] {
                    GetDeviceQuery});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetDevice(DeviceIDStruct GetDeviceQuery, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetDevice", new object[] {
                    GetDeviceQuery}, callback, asyncState);
    }
    
    /// <remarks/>
    public DeviceDetailsStruct EndGetDevice(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((DeviceDetailsStruct)(results[0]));
    }
    
    /// <remarks/>
    public void GetDeviceAsync(DeviceIDStruct GetDeviceQuery) {
        this.GetDeviceAsync(GetDeviceQuery, null);
    }
    
    /// <remarks/>
    public void GetDeviceAsync(DeviceIDStruct GetDeviceQuery, object userState) {
        if ((this.GetDeviceOperationCompleted == null)) {
            this.GetDeviceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDeviceOperationCompleted);
        }
        this.InvokeAsync("GetDevice", new object[] {
                    GetDeviceQuery}, this.GetDeviceOperationCompleted, userState);
    }
    
    private void OnGetDeviceOperationCompleted(object arg) {
        if ((this.GetDeviceCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetDeviceCompleted(this, new GetDeviceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:www.acslite.com/nbi:1.5", ResponseNamespace="urn:www.acslite.com/nbi:1.5", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("PaginationDetails")]
    public PaginationDetailsStruct GetDeviceHistory(GetDeviceQueryStruct DeviceHistoryQuery, OrderByList OrderByList, PaginationStruct Pagination, out HistoryDetailsList HistoryDetailsList) {
        object[] results = this.Invoke("GetDeviceHistory", new object[] {
                    DeviceHistoryQuery,
                    OrderByList,
                    Pagination});
        HistoryDetailsList = ((HistoryDetailsList)(results[1]));
        return ((PaginationDetailsStruct)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetDeviceHistory(GetDeviceQueryStruct DeviceHistoryQuery, OrderByList OrderByList, PaginationStruct Pagination, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetDeviceHistory", new object[] {
                    DeviceHistoryQuery,
                    OrderByList,
                    Pagination}, callback, asyncState);
    }
    
    /// <remarks/>
    public PaginationDetailsStruct EndGetDeviceHistory(System.IAsyncResult asyncResult, out HistoryDetailsList HistoryDetailsList) {
        object[] results = this.EndInvoke(asyncResult);
        HistoryDetailsList = ((HistoryDetailsList)(results[1]));
        return ((PaginationDetailsStruct)(results[0]));
    }
    
    /// <remarks/>
    public void GetDeviceHistoryAsync(GetDeviceQueryStruct DeviceHistoryQuery, OrderByList OrderByList, PaginationStruct Pagination) {
        this.GetDeviceHistoryAsync(DeviceHistoryQuery, OrderByList, Pagination, null);
    }
    
    /// <remarks/>
    public void GetDeviceHistoryAsync(GetDeviceQueryStruct DeviceHistoryQuery, OrderByList OrderByList, PaginationStruct Pagination, object userState) {
        if ((this.GetDeviceHistoryOperationCompleted == null)) {
            this.GetDeviceHistoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDeviceHistoryOperationCompleted);
        }
        this.InvokeAsync("GetDeviceHistory", new object[] {
                    DeviceHistoryQuery,
                    OrderByList,
                    Pagination}, this.GetDeviceHistoryOperationCompleted, userState);
    }
    
    private void OnGetDeviceHistoryOperationCompleted(object arg) {
        if ((this.GetDeviceHistoryCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetDeviceHistoryCompleted(this, new GetDeviceHistoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:www.acslite.com/nbi:1.5", ResponseNamespace="urn:www.acslite.com/nbi:1.5", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("Success")]
    public bool DeleteDevice(DeviceIDStruct DeviceID) {
        object[] results = this.Invoke("DeleteDevice", new object[] {
                    DeviceID});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDeleteDevice(DeviceIDStruct DeviceID, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("DeleteDevice", new object[] {
                    DeviceID}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndDeleteDevice(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void DeleteDeviceAsync(DeviceIDStruct DeviceID) {
        this.DeleteDeviceAsync(DeviceID, null);
    }
    
    /// <remarks/>
    public void DeleteDeviceAsync(DeviceIDStruct DeviceID, object userState) {
        if ((this.DeleteDeviceOperationCompleted == null)) {
            this.DeleteDeviceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteDeviceOperationCompleted);
        }
        this.InvokeAsync("DeleteDevice", new object[] {
                    DeviceID}, this.DeleteDeviceOperationCompleted, userState);
    }
    
    private void OnDeleteDeviceOperationCompleted(object arg) {
        if ((this.DeleteDeviceCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.DeleteDeviceCompleted(this, new DeleteDeviceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:www.acslite.com/nbi:1.5", ResponseNamespace="urn:www.acslite.com/nbi:1.5", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("PaginationDetails")]
    public PaginationDetailsStruct CustomSearch(SelectFieldList SelectFields, CriteriaList Criteria, CustomSearchOrderByList OrderByList, PaginationStruct Pagination, out ResultRecordList ResultRecords) {
        object[] results = this.Invoke("CustomSearch", new object[] {
                    SelectFields,
                    Criteria,
                    OrderByList,
                    Pagination});
        ResultRecords = ((ResultRecordList)(results[1]));
        return ((PaginationDetailsStruct)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCustomSearch(SelectFieldList SelectFields, CriteriaList Criteria, CustomSearchOrderByList OrderByList, PaginationStruct Pagination, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("CustomSearch", new object[] {
                    SelectFields,
                    Criteria,
                    OrderByList,
                    Pagination}, callback, asyncState);
    }
    
    /// <remarks/>
    public PaginationDetailsStruct EndCustomSearch(System.IAsyncResult asyncResult, out ResultRecordList ResultRecords) {
        object[] results = this.EndInvoke(asyncResult);
        ResultRecords = ((ResultRecordList)(results[1]));
        return ((PaginationDetailsStruct)(results[0]));
    }
    
    /// <remarks/>
    public void CustomSearchAsync(SelectFieldList SelectFields, CriteriaList Criteria, CustomSearchOrderByList OrderByList, PaginationStruct Pagination) {
        this.CustomSearchAsync(SelectFields, Criteria, OrderByList, Pagination, null);
    }
    
    /// <remarks/>
    public void CustomSearchAsync(SelectFieldList SelectFields, CriteriaList Criteria, CustomSearchOrderByList OrderByList, PaginationStruct Pagination, object userState) {
        if ((this.CustomSearchOperationCompleted == null)) {
            this.CustomSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCustomSearchOperationCompleted);
        }
        this.InvokeAsync("CustomSearch", new object[] {
                    SelectFields,
                    Criteria,
                    OrderByList,
                    Pagination}, this.CustomSearchOperationCompleted, userState);
    }
    
    private void OnCustomSearchOperationCompleted(object arg) {
        if ((this.CustomSearchCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CustomSearchCompleted(this, new CustomSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:www.acslite.com/nbi:1.5", ResponseNamespace="urn:www.acslite.com/nbi:1.5", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("PaginationDetails")]
    public PaginationDetailsStruct GetDeviceTypes(GetDeviceTypesQueryStruct DeviceTypeQuery, QueryType QueryType, OrderByList OrderByList, PaginationStruct Pagination, out DeviceTypeList DeviceTypes) {
        object[] results = this.Invoke("GetDeviceTypes", new object[] {
                    DeviceTypeQuery,
                    QueryType,
                    OrderByList,
                    Pagination});
        DeviceTypes = ((DeviceTypeList)(results[1]));
        return ((PaginationDetailsStruct)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetDeviceTypes(GetDeviceTypesQueryStruct DeviceTypeQuery, QueryType QueryType, OrderByList OrderByList, PaginationStruct Pagination, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetDeviceTypes", new object[] {
                    DeviceTypeQuery,
                    QueryType,
                    OrderByList,
                    Pagination}, callback, asyncState);
    }
    
    /// <remarks/>
    public PaginationDetailsStruct EndGetDeviceTypes(System.IAsyncResult asyncResult, out DeviceTypeList DeviceTypes) {
        object[] results = this.EndInvoke(asyncResult);
        DeviceTypes = ((DeviceTypeList)(results[1]));
        return ((PaginationDetailsStruct)(results[0]));
    }
    
    /// <remarks/>
    public void GetDeviceTypesAsync(GetDeviceTypesQueryStruct DeviceTypeQuery, QueryType QueryType, OrderByList OrderByList, PaginationStruct Pagination) {
        this.GetDeviceTypesAsync(DeviceTypeQuery, QueryType, OrderByList, Pagination, null);
    }
    
    /// <remarks/>
    public void GetDeviceTypesAsync(GetDeviceTypesQueryStruct DeviceTypeQuery, QueryType QueryType, OrderByList OrderByList, PaginationStruct Pagination, object userState) {
        if ((this.GetDeviceTypesOperationCompleted == null)) {
            this.GetDeviceTypesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDeviceTypesOperationCompleted);
        }
        this.InvokeAsync("GetDeviceTypes", new object[] {
                    DeviceTypeQuery,
                    QueryType,
                    OrderByList,
                    Pagination}, this.GetDeviceTypesOperationCompleted, userState);
    }
    
    private void OnGetDeviceTypesOperationCompleted(object arg) {
        if ((this.GetDeviceTypesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetDeviceTypesCompleted(this, new GetDeviceTypesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:www.acslite.com/nbi:1.5", ResponseNamespace="urn:www.acslite.com/nbi:1.5", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("DeviceType")]
    public DeviceTypeStruct GetDeviceType(GetDeviceTypeQueryStruct DeviceTypeQuery) {
        object[] results = this.Invoke("GetDeviceType", new object[] {
                    DeviceTypeQuery});
        return ((DeviceTypeStruct)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetDeviceType(GetDeviceTypeQueryStruct DeviceTypeQuery, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetDeviceType", new object[] {
                    DeviceTypeQuery}, callback, asyncState);
    }
    
    /// <remarks/>
    public DeviceTypeStruct EndGetDeviceType(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((DeviceTypeStruct)(results[0]));
    }
    
    /// <remarks/>
    public void GetDeviceTypeAsync(GetDeviceTypeQueryStruct DeviceTypeQuery) {
        this.GetDeviceTypeAsync(DeviceTypeQuery, null);
    }
    
    /// <remarks/>
    public void GetDeviceTypeAsync(GetDeviceTypeQueryStruct DeviceTypeQuery, object userState) {
        if ((this.GetDeviceTypeOperationCompleted == null)) {
            this.GetDeviceTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDeviceTypeOperationCompleted);
        }
        this.InvokeAsync("GetDeviceType", new object[] {
                    DeviceTypeQuery}, this.GetDeviceTypeOperationCompleted, userState);
    }
    
    private void OnGetDeviceTypeOperationCompleted(object arg) {
        if ((this.GetDeviceTypeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetDeviceTypeCompleted(this, new GetDeviceTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:www.acslite.com/nbi:1.5", ResponseNamespace="urn:www.acslite.com/nbi:1.5", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("Success")]
    public bool DeleteDeviceType(GetDeviceTypeQueryStruct DeviceTypeQuery) {
        object[] results = this.Invoke("DeleteDeviceType", new object[] {
                    DeviceTypeQuery});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDeleteDeviceType(GetDeviceTypeQueryStruct DeviceTypeQuery, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("DeleteDeviceType", new object[] {
                    DeviceTypeQuery}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndDeleteDeviceType(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void DeleteDeviceTypeAsync(GetDeviceTypeQueryStruct DeviceTypeQuery) {
        this.DeleteDeviceTypeAsync(DeviceTypeQuery, null);
    }
    
    /// <remarks/>
    public void DeleteDeviceTypeAsync(GetDeviceTypeQueryStruct DeviceTypeQuery, object userState) {
        if ((this.DeleteDeviceTypeOperationCompleted == null)) {
            this.DeleteDeviceTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteDeviceTypeOperationCompleted);
        }
        this.InvokeAsync("DeleteDeviceType", new object[] {
                    DeviceTypeQuery}, this.DeleteDeviceTypeOperationCompleted, userState);
    }
    
    private void OnDeleteDeviceTypeOperationCompleted(object arg) {
        if ((this.DeleteDeviceTypeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.DeleteDeviceTypeCompleted(this, new DeleteDeviceTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:www.acslite.com/nbi:1.5", ResponseNamespace="urn:www.acslite.com/nbi:1.5", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("DeviceType")]
    public DeviceTypeStruct ImportDeviceType(string DeviceTypeDefinition) {
        object[] results = this.Invoke("ImportDeviceType", new object[] {
                    DeviceTypeDefinition});
        return ((DeviceTypeStruct)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginImportDeviceType(string DeviceTypeDefinition, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ImportDeviceType", new object[] {
                    DeviceTypeDefinition}, callback, asyncState);
    }
    
    /// <remarks/>
    public DeviceTypeStruct EndImportDeviceType(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((DeviceTypeStruct)(results[0]));
    }
    
    /// <remarks/>
    public void ImportDeviceTypeAsync(string DeviceTypeDefinition) {
        this.ImportDeviceTypeAsync(DeviceTypeDefinition, null);
    }
    
    /// <remarks/>
    public void ImportDeviceTypeAsync(string DeviceTypeDefinition, object userState) {
        if ((this.ImportDeviceTypeOperationCompleted == null)) {
            this.ImportDeviceTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImportDeviceTypeOperationCompleted);
        }
        this.InvokeAsync("ImportDeviceType", new object[] {
                    DeviceTypeDefinition}, this.ImportDeviceTypeOperationCompleted, userState);
    }
    
    private void OnImportDeviceTypeOperationCompleted(object arg) {
        if ((this.ImportDeviceTypeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ImportDeviceTypeCompleted(this, new ImportDeviceTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:www.acslite.com/nbi:1.5")]
public partial class DeviceIDStruct {
    
    private string manufacturerField;
    
    private string oUIField;
    
    private string productClassField;
    
    private string serialNumberField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Manufacturer {
        get {
            return this.manufacturerField;
        }
        set {
            this.manufacturerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OUI {
        get {
            return this.oUIField;
        }
        set {
            this.oUIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ProductClass {
        get {
            return this.productClassField;
        }
        set {
            this.productClassField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SerialNumber {
        get {
            return this.serialNumberField;
        }
        set {
            this.serialNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:www.acslite.com/nbi:1.5")]
public partial class DeviceTypeStruct {
    
    private string oUIField;
    
    private string productClassField;
    
    private string fWVersionField;
    
    private string manufacturerField;
    
    private string descriptionField;
    
    private string dataModelIDField;
    
    private string hTTPAuthField;
    
    private string hTTPSAuthField;
    
    private bool dataModelDiscoveryEnabledField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OUI {
        get {
            return this.oUIField;
        }
        set {
            this.oUIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ProductClass {
        get {
            return this.productClassField;
        }
        set {
            this.productClassField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FWVersion {
        get {
            return this.fWVersionField;
        }
        set {
            this.fWVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Manufacturer {
        get {
            return this.manufacturerField;
        }
        set {
            this.manufacturerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DataModelID {
        get {
            return this.dataModelIDField;
        }
        set {
            this.dataModelIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HTTPAuth {
        get {
            return this.hTTPAuthField;
        }
        set {
            this.hTTPAuthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HTTPSAuth {
        get {
            return this.hTTPSAuthField;
        }
        set {
            this.hTTPSAuthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool DataModelDiscoveryEnabled {
        get {
            return this.dataModelDiscoveryEnabledField;
        }
        set {
            this.dataModelDiscoveryEnabledField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:www.acslite.com/nbi:1.5")]
public partial class GetDeviceTypeQueryStruct {
    
    private string oUIField;
    
    private string productClassField;
    
    private string fWVersionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OUI {
        get {
            return this.oUIField;
        }
        set {
            this.oUIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ProductClass {
        get {
            return this.productClassField;
        }
        set {
            this.productClassField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FWVersion {
        get {
            return this.fWVersionField;
        }
        set {
            this.fWVersionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:www.acslite.com/nbi:1.5")]
public partial class GetDeviceTypesQueryStruct {
    
    private string oUIField;
    
    private string productClassField;
    
    private string fWVersionField;
    
    private string manufacturerField;
    
    private string descriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OUI {
        get {
            return this.oUIField;
        }
        set {
            this.oUIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ProductClass {
        get {
            return this.productClassField;
        }
        set {
            this.productClassField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FWVersion {
        get {
            return this.fWVersionField;
        }
        set {
            this.fWVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Manufacturer {
        get {
            return this.manufacturerField;
        }
        set {
            this.manufacturerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:www.acslite.com/nbi:1.5")]
public partial class GetDeviceQueryStruct {
    
    private string oUIField;
    
    private string productClassField;
    
    private string serialNumberField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OUI {
        get {
            return this.oUIField;
        }
        set {
            this.oUIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ProductClass {
        get {
            return this.productClassField;
        }
        set {
            this.productClassField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SerialNumber {
        get {
            return this.serialNumberField;
        }
        set {
            this.serialNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:www.acslite.com/nbi:1.5")]
public partial class DeviceDetailsStruct {
    
    private string oUIField;
    
    private string productClassField;
    
    private string serialNumberField;
    
    private string descriptionField;
    
    private bool commlogEnabledField;
    
    private System.DateTime createdDTField;
    
    private System.DateTime firstContactedDTField;
    
    private System.DateTime lastContactedDTField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OUI {
        get {
            return this.oUIField;
        }
        set {
            this.oUIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ProductClass {
        get {
            return this.productClassField;
        }
        set {
            this.productClassField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SerialNumber {
        get {
            return this.serialNumberField;
        }
        set {
            this.serialNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool CommlogEnabled {
        get {
            return this.commlogEnabledField;
        }
        set {
            this.commlogEnabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime CreatedDT {
        get {
            return this.createdDTField;
        }
        set {
            this.createdDTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime FirstContactedDT {
        get {
            return this.firstContactedDTField;
        }
        set {
            this.firstContactedDTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime LastContactedDT {
        get {
            return this.lastContactedDTField;
        }
        set {
            this.lastContactedDTField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:www.acslite.com/nbi:1.5")]
public partial class PaginationDetailsStruct {
    
    private uint recordStartField;
    
    private uint recordCountField;
    
    private uint totalRecordsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public uint RecordStart {
        get {
            return this.recordStartField;
        }
        set {
            this.recordStartField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public uint RecordCount {
        get {
            return this.recordCountField;
        }
        set {
            this.recordCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public uint TotalRecords {
        get {
            return this.totalRecordsField;
        }
        set {
            this.totalRecordsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:www.acslite.com/nbi:1.5")]
public partial class PaginationStruct {
    
    private uint recordStartField;
    
    private bool recordStartFieldSpecified;
    
    private uint recordCountField;
    
    private bool recordCountFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public uint RecordStart {
        get {
            return this.recordStartField;
        }
        set {
            this.recordStartField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RecordStartSpecified {
        get {
            return this.recordStartFieldSpecified;
        }
        set {
            this.recordStartFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public uint RecordCount {
        get {
            return this.recordCountField;
        }
        set {
            this.recordCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RecordCountSpecified {
        get {
            return this.recordCountFieldSpecified;
        }
        set {
            this.recordCountFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:www.acslite.com/nbi:1.5")]
public partial class SearchDevicesQueryStruct {
    
    private string oUIField;
    
    private string productClassField;
    
    private string serialNumberField;
    
    private string descriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OUI {
        get {
            return this.oUIField;
        }
        set {
            this.oUIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ProductClass {
        get {
            return this.productClassField;
        }
        set {
            this.productClassField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SerialNumber {
        get {
            return this.serialNumberField;
        }
        set {
            this.serialNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DeviceTypeList))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ResultRecordList))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ResultFieldList))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CustomSearchOrderByList))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CriteriaList))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(RequiredCriteriaList))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(SelectFieldList))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(HistoryDetailsList))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderByList))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DeviceDetailsList))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ParameterNameList))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ParameterDetailsList))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CPERequestParameterList))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(FlagValueList))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(FlagNameList))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(FlagDetailsList))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ParameterAttributeList))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AccessList))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ParameterInfoList))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/soap/encoding/")]
public partial class Array {
    
    private System.Xml.XmlElement[] anyField;
    
    private string arrayTypeField;
    
    private string offsetField;
    
    private bool offsetFieldSpecified;
    
    private string idField;
    
    private string hrefField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string arrayType {
        get {
            return this.arrayTypeField;
        }
        set {
            this.arrayTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string offset {
        get {
            return this.offsetField;
        }
        set {
            this.offsetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool offsetSpecified {
        get {
            return this.offsetFieldSpecified;
        }
        set {
            this.offsetFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string href {
        get {
            return this.hrefField;
        }
        set {
            this.hrefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:www.acslite.com/nbi:1.5")]
public partial class DeviceTypeList : Array {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:www.acslite.com/nbi:1.5")]
public partial class ResultRecordList : Array {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:www.acslite.com/nbi:1.5")]
public partial class ResultFieldList : Array {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:www.acslite.com/nbi:1.5")]
public partial class CustomSearchOrderByList : Array {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:www.acslite.com/nbi:1.5")]
public partial class CriteriaList : Array {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:www.acslite.com/nbi:1.5")]
public partial class RequiredCriteriaList : Array {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:www.acslite.com/nbi:1.5")]
public partial class SelectFieldList : Array {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:www.acslite.com/nbi:1.5")]
public partial class HistoryDetailsList : Array {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:www.acslite.com/nbi:1.5")]
public partial class OrderByList : Array {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:www.acslite.com/nbi:1.5")]
public partial class DeviceDetailsList : Array {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:www.acslite.com/nbi:1.5")]
public partial class ParameterNameList : Array {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:www.acslite.com/nbi:1.5")]
public partial class ParameterDetailsList : Array {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:www.acslite.com/nbi:1.5")]
public partial class CPERequestParameterList : Array {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:www.acslite.com/nbi:1.5")]
public partial class FlagValueList : Array {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:www.acslite.com/nbi:1.5")]
public partial class FlagNameList : Array {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:www.acslite.com/nbi:1.5")]
public partial class FlagDetailsList : Array {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:www.acslite.com/nbi:1.5")]
public partial class ParameterAttributeList : Array {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:www.acslite.com/nbi:1.5")]
public partial class AccessList : Array {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:www.acslite.com/nbi:1.5")]
public partial class ParameterInfoList : Array {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:www.acslite.com/nbi:1.5")]
public partial class DevicePropertiesStruct {
    
    private string descriptionField;
    
    private string usernameField;
    
    private string passwordField;
    
    private string cRUsernameField;
    
    private string cRPasswordField;
    
    private bool commLogEnabledField;
    
    private bool commLogEnabledFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Username {
        get {
            return this.usernameField;
        }
        set {
            this.usernameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CRUsername {
        get {
            return this.cRUsernameField;
        }
        set {
            this.cRUsernameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CRPassword {
        get {
            return this.cRPasswordField;
        }
        set {
            this.cRPasswordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool CommLogEnabled {
        get {
            return this.commLogEnabledField;
        }
        set {
            this.commLogEnabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CommLogEnabledSpecified {
        get {
            return this.commLogEnabledFieldSpecified;
        }
        set {
            this.commLogEnabledFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:www.acslite.com/nbi:1.5")]
public enum CPERequestMethod {
    
    /// <remarks/>
    GetParameterValues,
    
    /// <remarks/>
    SetParameterValues,
    
    /// <remarks/>
    GetParameterAttributes,
    
    /// <remarks/>
    SetParameterAttributes,
    
    /// <remarks/>
    GetParameterNames,
    
    /// <remarks/>
    AddObject,
    
    /// <remarks/>
    DeleteObject,
    
    /// <remarks/>
    Download,
    
    /// <remarks/>
    Upload,
    
    /// <remarks/>
    Reboot,
    
    /// <remarks/>
    FactoryReset,
    
    /// <remarks/>
    GetRPCMethods,
    
    /// <remarks/>
    EndSession,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:www.acslite.com/nbi:1.5")]
public enum QueryType {
    
    /// <remarks/>
    match,
    
    /// <remarks/>
    search,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void RegisterDeviceCompletedEventHandler(object sender, RegisterDeviceCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class RegisterDeviceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal RegisterDeviceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void GetDeviceFlagsCompletedEventHandler(object sender, GetDeviceFlagsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetDeviceFlagsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetDeviceFlagsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public FlagDetailsList Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((FlagDetailsList)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void SetDeviceFlagsCompletedEventHandler(object sender, SetDeviceFlagsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SetDeviceFlagsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SetDeviceFlagsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void SendConnectionRequestCompletedEventHandler(object sender, SendConnectionRequestCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SendConnectionRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SendConnectionRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void QueueCPERequestCompletedEventHandler(object sender, QueueCPERequestCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class QueueCPERequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal QueueCPERequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void GetDeviceCachedParamsCompletedEventHandler(object sender, GetDeviceCachedParamsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetDeviceCachedParamsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetDeviceCachedParamsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ParameterDetailsList Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ParameterDetailsList)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void SearchDevicesCompletedEventHandler(object sender, SearchDevicesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SearchDevicesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SearchDevicesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public PaginationDetailsStruct Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((PaginationDetailsStruct)(this.results[0]));
        }
    }
    
    /// <remarks/>
    public DeviceDetailsList DeviceDetailsList {
        get {
            this.RaiseExceptionIfNecessary();
            return ((DeviceDetailsList)(this.results[1]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void GetDeviceCompletedEventHandler(object sender, GetDeviceCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetDeviceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetDeviceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public DeviceDetailsStruct Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((DeviceDetailsStruct)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void GetDeviceHistoryCompletedEventHandler(object sender, GetDeviceHistoryCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetDeviceHistoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetDeviceHistoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public PaginationDetailsStruct Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((PaginationDetailsStruct)(this.results[0]));
        }
    }
    
    /// <remarks/>
    public HistoryDetailsList HistoryDetailsList {
        get {
            this.RaiseExceptionIfNecessary();
            return ((HistoryDetailsList)(this.results[1]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void DeleteDeviceCompletedEventHandler(object sender, DeleteDeviceCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DeleteDeviceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal DeleteDeviceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void CustomSearchCompletedEventHandler(object sender, CustomSearchCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CustomSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CustomSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public PaginationDetailsStruct Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((PaginationDetailsStruct)(this.results[0]));
        }
    }
    
    /// <remarks/>
    public ResultRecordList ResultRecords {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ResultRecordList)(this.results[1]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void GetDeviceTypesCompletedEventHandler(object sender, GetDeviceTypesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetDeviceTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetDeviceTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public PaginationDetailsStruct Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((PaginationDetailsStruct)(this.results[0]));
        }
    }
    
    /// <remarks/>
    public DeviceTypeList DeviceTypes {
        get {
            this.RaiseExceptionIfNecessary();
            return ((DeviceTypeList)(this.results[1]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void GetDeviceTypeCompletedEventHandler(object sender, GetDeviceTypeCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetDeviceTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetDeviceTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public DeviceTypeStruct Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((DeviceTypeStruct)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void DeleteDeviceTypeCompletedEventHandler(object sender, DeleteDeviceTypeCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DeleteDeviceTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal DeleteDeviceTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void ImportDeviceTypeCompletedEventHandler(object sender, ImportDeviceTypeCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ImportDeviceTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ImportDeviceTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public DeviceTypeStruct Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((DeviceTypeStruct)(this.results[0]));
        }
    }
}
